name: fcg
description: Advanced dart/flutter dev tool for generating page, widget, model, repository, and bloc etc.
version: 1.0.1
homepage: https://github.com/pravinkumarputta/fcg

executables:
  fcg:

environment:
  sdk: '>=2.16.2 <3.0.0'


dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.2

dependencies: 
  args: ^2.3.0
  dart_style: ^2.2.2
  json_ast: ^1.0.6
  path: ^1.8.1
  quiver: ^3.0.1+1
